name: 'dart_highlightjs'
version: 0.0.1
description: Simple example of Dart 1.13+ js interop, calling into highlightjs.org library API.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  js: ^0.6.0

transformers:
- dart_to_js_script_rewriter
